version: "2"
services:
  Nodejs:
    restart: always
    image: dananggeek/skripsi:latest
    container_name: App
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongoo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
